// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN4tlqlXJBv-iItPOw8aoUqpWFq4K0dSc',
    appId: '1:656859925893:web:0f68c3821c43caee1f88ec',
    messagingSenderId: '656859925893',
    projectId: 'task-proj-12864',
    authDomain: 'task-proj-12864.firebaseapp.com',
    storageBucket: 'task-proj-12864.firebasestorage.app',
    measurementId: 'G-X0WPHM82E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVI8U_CKsJnui7voNOqRbMCUd_2hDAzoc',
    appId: '1:656859925893:android:363bcc4c7ae48b2f1f88ec',
    messagingSenderId: '656859925893',
    projectId: 'task-proj-12864',
    storageBucket: 'task-proj-12864.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYONjCts3JJBD5arx6VGPB32HBJwU4AgY',
    appId: '1:656859925893:ios:5c0b3eaa304d286b1f88ec',
    messagingSenderId: '656859925893',
    projectId: 'task-proj-12864',
    storageBucket: 'task-proj-12864.firebasestorage.app',
    iosBundleId: 'com.example.taskProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYONjCts3JJBD5arx6VGPB32HBJwU4AgY',
    appId: '1:656859925893:ios:5c0b3eaa304d286b1f88ec',
    messagingSenderId: '656859925893',
    projectId: 'task-proj-12864',
    storageBucket: 'task-proj-12864.firebasestorage.app',
    iosBundleId: 'com.example.taskProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN4tlqlXJBv-iItPOw8aoUqpWFq4K0dSc',
    appId: '1:656859925893:web:312ffd7906dafca11f88ec',
    messagingSenderId: '656859925893',
    projectId: 'task-proj-12864',
    authDomain: 'task-proj-12864.firebaseapp.com',
    storageBucket: 'task-proj-12864.firebasestorage.app',
    measurementId: 'G-4X07FV2GZC',
  );
}
